import { spawn } from "node:child_process";
import * as esbuild from "esbuild";
import { describe, expect, it, vi } from "vitest";
import { generateRuntime as generateRootRuntime } from "../../src/compiler/runtime-template";
import {
  generateBashWrapper as generateRootBashWrapper,
  generatePowerShellWrapper,
} from "../../src/compiler/wrapper-template";
import { buildHandlers } from "../src/playground/compiler/build-handlers";
import { createCompiler } from "../src/playground/compiler/compiler.worker";
import {
  annotatePureDefineHandlers,
  generateBashWrapper,
  generateRuntime,
} from "../src/playground/compiler/virtual-modules";
import { readFile } from "node:fs/promises";

const starter = `
  import { defineHandler } from "@typed-rocks/typed-claude-hooks"

  export const blockRm = defineHandler("PreToolUse", { matcher: "Bash" }, async (input) => ({
    hookSpecificOutput: input.tool_input.command.includes("rm ")
      ? { permissionDecision: "deny", permissionDecisionReason: "Blocked rm" }
      : undefined,
  }))
`;

describe("buildHandlers", () => {
  it("uses a browser-worker-safe TypeScript namespace import", async () => {
    const implementation = await readFile(
      new URL("../src/playground/compiler/virtual-modules.ts", import.meta.url),
      "utf8",
    );

    expect(implementation).toContain('import * as ts from "typescript"');
    expect(implementation).not.toContain('import ts from "typescript"');
    expect(implementation).not.toContain("ts.createCompilerHost(");
  });
  it("builds an executable Node ESM artifact with its default wrapper and exact settings path", async () => {
    const result = await buildHandlers(
      { source: starter, requestId: 7 },
      esbuild,
    );

    expect(result.requestId).toBe(7);
    expect(result.status).toBe("success");
    expect(result.diagnostics).toEqual([]);
    expect(result.handlers).toEqual([
      { name: "blockRm", event: "PreToolUse", matcher: "Bash" },
    ]);
    expect(result.artifacts).toHaveLength(1);

    const artifact = result.artifacts[0];
    expect(artifact.filePath).toBe(
      ".claude/hooks/typed-claude-hooks/PreToolUse/blockRm.mjs",
    );
    expect(artifact.contents).toContain(
      "// Generated by typed-claude-hooks - do not edit",
    );
    expect(artifact.contents).toContain("process.stdin");
    expect(artifact.wrapper).toEqual({
      filePath: ".claude/hooks/typed-claude-hooks/PreToolUse/blockRm.sh",
      contents: expect.stringContaining(
        'exec node "$SCRIPT_DIR/blockRm.mjs" "$@"',
      ),
    });
    expect(result.settings).toEqual({
      hooks: {
        PreToolUse: [
          {
            matcher: "Bash",
            hooks: [
              {
                type: "command",
                command:
                  '"${CLAUDE_PROJECT_DIR}/.claude/hooks/typed-claude-hooks/PreToolUse/blockRm.sh"',
              },
            ],
          },
        ],
      },
    });

    const execution = await executeArtifact(artifact.contents, {
      hook_event_name: "PreToolUse",
      tool_input: { command: "rm important.txt" },
    });
    expect(execution.code).toBe(0);
    expect(JSON.parse(execution.stdout).hookSpecificOutput).toEqual({
      permissionDecision: "deny",
      permissionDecisionReason: "Blocked rm",
      hookEventName: "PreToolUse",
    });
  });

  it("keeps Bash wrappers and runtime templates in exact parity with the root compiler", () => {
    expect(generateBashWrapper("handler.mjs")).toBe(
      generateRootBashWrapper("handler.mjs", "node"),
    );
    expect(generateRuntime("handler.handler")).toBe(
      generateRootRuntime("handler.handler"),
    );
  });

  it("builds handlers separately and tree-shakes sibling handler bodies", async () => {
    const result = await buildHandlers(
      {
        requestId: "multi",
        source: `
        import { defineHandler } from "@typed-rocks/typed-claude-hooks"
        export const before = defineHandler("PreToolUse", {
          matcher: "Bash",
          timeout: 5000,
          statusMessage: "Checking",
        }, async () => ({ systemMessage: "before-only-marker" }))
        export const stopped = defineHandler("Stop", { once: true }, async () => ({
          systemMessage: "stop-only-marker",
        }))
      `,
      },
      esbuild,
    );

    expect(result.status).toBe("success");
    expect(result.artifacts).toHaveLength(2);
    const before = result.artifacts.find(({ name }) => name === "before");
    const stopped = result.artifacts.find(({ name }) => name === "stopped");
    expect(before?.contents).toContain("before-only-marker");
    expect(before?.contents).not.toContain("stop-only-marker");
    expect(stopped?.contents).toContain("stop-only-marker");
    expect(stopped?.contents).not.toContain("before-only-marker");
    expect(result.settings.hooks.Stop[0].hooks[0]).toMatchObject({
      once: true,
    });
    expect(result.settings.hooks.PreToolUse[0].hooks[0]).toMatchObject({
      timeout: 5000,
      statusMessage: "Checking",
    });
  });

  it("does not mark lexically shadowed defineHandler calls as pure", () => {
    const source = `
      import { defineHandler } from "@typed-rocks/typed-claude-hooks"
      function retainSideEffect(defineHandler) {
        defineHandler("shadowed-local-call")
      }
      export const stopped = defineHandler("Stop", async () => ({}))
    `;
    const annotated = annotatePureDefineHandlers(source);

    expect(annotated).toContain('defineHandler("shadowed-local-call")');
    expect(annotated).not.toContain(
      '/* @__PURE__ */ defineHandler("shadowed-local-call")',
    );
    expect(annotated).toContain(
      '/* @__PURE__ */ defineHandler("Stop", async () => ({}))',
    );
  });

  it("retains shadowed defineHandler side effects while tree-shaking sibling handlers", async () => {
    const result = await buildHandlers(
      {
        requestId: "shadowed-build",
        source: `
          import { defineHandler } from "@typed-rocks/typed-claude-hooks"
          {
            const defineHandler = (marker) => console.error(marker)
            defineHandler("shadowed-side-effect-marker")
          }
          export const stopped = defineHandler("Stop", async () => ({ systemMessage: "selected-marker" }))
          export const sibling = defineHandler("SessionStart", async () => ({ systemMessage: "sibling-marker" }))
        `,
      },
      esbuild,
    );

    const stopped = result.artifacts.find(({ name }) => name === "stopped");
    expect(stopped?.contents).toContain("shadowed-side-effect-marker");
    expect(stopped?.contents).toContain("selected-marker");
    expect(stopped?.contents).not.toContain("sibling-marker");
  });

  it("retains external node imports in generated artifacts", async () => {
    const result = await buildHandlers(
      {
        requestId: 2,
        source: `
        import { basename } from "node:path"
        import { defineHandler } from "@typed-rocks/typed-claude-hooks"
        export const stopped = defineHandler("Stop", async () => ({ systemMessage: basename("/tmp/file") }))
      `,
      },
      esbuild,
    );

    expect(result.status).toBe("success");
    expect(result.artifacts[0].contents).toMatch(/from\s+["']node:path["']/);
  });

  it("emits a PowerShell wrapper and settings command for PowerShell handlers", async () => {
    const result = await buildHandlers(
      {
        requestId: "powershell",
        source: `
          import { defineHandler } from "@typed-rocks/typed-claude-hooks"
          export const stopped = defineHandler("Stop", { shell: "powershell" }, async () => ({}))
        `,
      },
      esbuild,
    );

    expect(result.status).toBe("success");
    expect(result.artifacts[0].wrapper).toEqual({
      filePath: ".claude/hooks/typed-claude-hooks/Stop/stopped.ps1",
      contents: generatePowerShellWrapper("stopped.mjs", "node"),
    });
    expect(result.settings).toEqual({
      hooks: {
        Stop: [
          {
            hooks: [
              {
                type: "command",
                command:
                  '& "${CLAUDE_PROJECT_DIR}/.claude/hooks/typed-claude-hooks/Stop/stopped.ps1"',
                shell: "powershell",
              },
            ],
          },
        ],
      },
    });
  });

  it.each([
    [
      "unsupported imports",
      'import value from "left-pad"',
      "PLAYGROUND_UNSUPPORTED_IMPORT",
    ],
    ["malformed TypeScript", "export const =", "TS"],
    ["no handlers", "export type Empty = string", "PLAYGROUND_NO_HANDLERS"],
  ])(
    "returns diagnostics without invoking esbuild for %s",
    async (_name, invalidSource, code) => {
      const build = async () => {
        throw new Error("build should not run");
      };
      const result = await buildHandlers(
        { source: invalidSource, requestId: 3 },
        { build },
      );

      expect(result.status).toBe("error");
      expect(result.artifacts).toEqual([]);
      expect(result.settings).toEqual({ hooks: {} });
      expect(
        result.diagnostics.some((diagnostic) =>
          diagnostic.code.startsWith(code),
        ),
      ).toBe(true);
    },
  );

  it("converts esbuild failures into serializable diagnostics", async () => {
    const result = await buildHandlers(
      { source: starter, requestId: 4 },
      {
        build: async () => {
          throw new Error("esbuild initialization failed");
        },
      },
    );

    expect(result.status).toBe("error");
    expect(result.diagnostics).toEqual([
      expect.objectContaining({
        code: "PLAYGROUND_BUILD_FAILED",
        message: "esbuild initialization failed",
      }),
    ]);
  });

  it("preserves structured esbuild error locations and source text", async () => {
    const error = Object.assign(new Error("Build failed with 1 error"), {
      errors: [
        {
          text: 'Could not resolve "node:missing"',
          location: {
            file: "hooks.config.ts",
            line: 4,
            column: 11,
            length: 14,
            lineText: 'import x from "node:missing"',
          },
        },
      ],
    });
    const result = await buildHandlers(
      { source: starter, requestId: "located-error" },
      { build: async () => Promise.reject(error) },
    );

    expect(result.diagnostics).toEqual([
      expect.objectContaining({
        code: "PLAYGROUND_BUILD_FAILED",
        message: 'Could not resolve "node:missing"',
        fileName: "hooks.config.ts",
        sourceLine: 'import x from "node:missing"',
        start: expect.objectContaining({ line: 4, column: 12 }),
        end: expect.objectContaining({ line: 4, column: 26 }),
      }),
    ]);
  });

  it("maps real esbuild virtual-config errors to the requested file name", async () => {
    const source = [
      'import { defineHandler } from "@typed-rocks/typed-claude-hooks"',
      'import { Runtime } from "@typed-rocks/typed-claude-hooks/types"',
      'export const stopped = defineHandler("Stop", async () => ({ systemMessage: String(Runtime) }))',
    ].join("\n");
    const result = await buildHandlers(
      { source, fileName: "custom-hooks.ts", requestId: "real-location" },
      esbuild,
    );

    expect(result.status).toBe("error");
    expect(result.diagnostics[0]).toMatchObject({
      fileName: "custom-hooks.ts",
      start: { line: 2, column: 25 },
      sourceLine: 'import { Runtime } from "@typed-rocks/typed-claude-hooks/types"',
    });
  });

  it("initializes esbuild once across requests", async () => {
    let initializationCount = 0;
    const compile = createCompiler(
      {
        ...esbuild,
        initialize: async () => {
          initializationCount += 1;
        },
      },
      "esbuild.wasm",
    );

    const first = await compile({
      type: "compile",
      source: starter,
      requestId: 10,
    });
    const second = await compile({
      type: "compile",
      source: starter,
      requestId: 11,
    });

    expect(first.status).toBe("success");
    expect(second.status).toBe("success");
    expect(initializationCount).toBe(1);
  });

  it("keeps only the active and latest pending compile requests", async () => {
    let active = 0;
    let maxActive = 0;
    const buildCalls: number[] = [];
    let releaseFirst: (() => void) | undefined;
    const compile = createCompiler(
      {
        initialize: async () => {},
        build: async () => {
          active += 1;
          maxActive = Math.max(maxActive, active);
          buildCalls.push(buildCalls.length + 1);
          if (buildCalls.length === 1) {
            await new Promise<void>((resolve) => {
              releaseFirst = resolve;
            });
          }
          active -= 1;
          return {
            errors: [],
            warnings: [],
            outputFiles: [
              {
                text: "output",
                contents: new Uint8Array(),
                path: "handler.mjs",
                hash: "",
              },
            ],
            metafile: undefined,
            mangleCache: undefined,
          };
        },
      },
      "esbuild.wasm",
    );

    const first = compile({ type: "compile", source: `${starter}\n// request-one`, requestId: 21 });
    await vi.waitFor(() => expect(buildCalls).toEqual([1]));
    const second = compile({ type: "compile", source: `${starter}\n// request-two`, requestId: 22 });
    const third = compile({ type: "compile", source: `${starter}\n// request-three`, requestId: 23 });
    await expect(second).resolves.toMatchObject({ requestId: 22, status: "superseded" });
    releaseFirst?.();
    const responses = await Promise.all([first, third]);

    expect(maxActive).toBe(1);
    expect(buildCalls).toEqual([1, 2]);
    expect(responses.map(({ requestId }) => requestId)).toEqual([21, 23]);
  });

  it("returns request-scoped diagnostics when esbuild initialization fails", async () => {
    const compile = createCompiler(
      {
        build: esbuild.build,
        initialize: async () => {
          throw new Error("WASM unavailable");
        },
      },
      "missing.wasm",
    );

    const first = await compile({
      type: "compile",
      source: starter,
      requestId: 12,
    });
    const second = await compile({
      type: "compile",
      source: starter,
      requestId: 13,
    });

    expect(first).toEqual(
      expect.objectContaining({ requestId: 12, status: "error" }),
    );
    expect(second).toEqual(
      expect.objectContaining({ requestId: 13, status: "error" }),
    );
    expect(first.diagnostics[0]).toMatchObject({
      code: "PLAYGROUND_INITIALIZATION_FAILED",
      message: "WASM unavailable",
    });
  });
});

function executeArtifact(
  contents: string,
  input: object,
): Promise<{ code: number | null; stdout: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [
      "--input-type=module",
      "--eval",
      contents,
    ]);
    const stdout: Buffer[] = [];
    child.stdout.on("data", (chunk) => stdout.push(chunk));
    child.on("error", reject);
    child.on("close", (code) =>
      resolve({ code, stdout: Buffer.concat(stdout).toString("utf8") }),
    );
    child.stdin.end(JSON.stringify(input));
  });
}
