import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { bundleHandlers } from "../../src/compiler/bundle-handlers.js";
import { extractHandlers } from "../../src/compiler/extract-handlers.js";
import { loadConfig } from "../../src/compiler/load-config.js";

const FIXTURE_PATH = resolve(
  import.meta.dirname,
  "../fixtures/sample-hooks.config.ts",
);
const OUTPUT_DIR = resolve(import.meta.dirname, "../fixtures/.output-hooks");

describe("bundleHandlers", () => {
  it("compiles each handler to a self-contained JS file", async () => {
    rmSync(OUTPUT_DIR, { recursive: true, force: true });
    mkdirSync(OUTPUT_DIR, { recursive: true });

    const loaded = await loadConfig(FIXTURE_PATH);
    const handlers = extractHandlers(loaded);

    const files = await bundleHandlers({
      configPath: FIXTURE_PATH,
      handlers,
      hooksDir: OUTPUT_DIR,
      runtime: "node",
    });

    expect(existsSync(resolve(OUTPUT_DIR, "runtime.mjs"))).toBe(false);
    expect(
      existsSync(resolve(OUTPUT_DIR, "PreToolUse/blockDangerous.mjs")),
    ).toBe(true);
    expect(existsSync(resolve(OUTPUT_DIR, "Stop/onStop.mjs"))).toBe(true);
    expect(
      existsSync(resolve(OUTPUT_DIR, "PreToolUse/blockDangerous.sh")),
    ).toBe(true);
    expect(existsSync(resolve(OUTPUT_DIR, "Stop/onStop.sh"))).toBe(true);

    const handlerCode = readFileSync(
      resolve(OUTPUT_DIR, "PreToolUse/blockDangerous.mjs"),
      "utf-8",
    );
    expect(handlerCode).toContain("process.stdin");
    expect(handlerCode).toContain("Generated by typed-claude-hooks");

    const wrapperCode = readFileSync(
      resolve(OUTPUT_DIR, "PreToolUse/blockDangerous.sh"),
      "utf-8",
    );
    expect(wrapperCode).toContain("#!/bin/sh");
    expect(wrapperCode).toContain("command -v node");
    expect(wrapperCode).toContain("exit 2");
    expect(wrapperCode).toContain("blockDangerous.mjs");

    expect(files).toHaveLength(2);
    expect(files[0].fileName).toBe("blockDangerous.mjs");
    expect(files[0].event).toBe("PreToolUse");

    rmSync(OUTPUT_DIR, { recursive: true, force: true });
  });
});
