import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import * as esbuild from "esbuild";
import { describe, expect, it, vi } from "vitest";
import { bundleHandlers } from "../../src/compiler/bundle-handlers.js";
import { extractHandlers } from "../../src/compiler/extract-handlers.js";
import { loadConfig } from "../../src/compiler/load-config.js";

const FIXTURE_PATH = resolve(
  import.meta.dirname,
  "../fixtures/sample-hooks.config.ts",
);
const RE_EXPORT_FIXTURE_PATH = resolve(
  import.meta.dirname,
  "../fixtures/configs/re-export.config.ts",
);
const RE_EXPORTED_HANDLERS_PATH = resolve(
  import.meta.dirname,
  "../fixtures/configs/re-exported-handlers.ts",
);
const OUTPUT_DIR = resolve(import.meta.dirname, "../fixtures/.output-hooks");
vi.mock("esbuild", async (importOriginal) => {
  const actual = await importOriginal<typeof esbuild>();
  return { ...actual, build: vi.fn(actual.build) };
});

describe("bundleHandlers", () => {
  it("compiles each handler to a self-contained JS file", async () => {
    rmSync(OUTPUT_DIR, { recursive: true, force: true });
    mkdirSync(OUTPUT_DIR, { recursive: true });

    const sourceBefore = readFileSync(FIXTURE_PATH, "utf8");
    expect(sourceBefore).toContain('"defineHandler("');
    expect(sourceBefore).toContain("`defineHandler(`");
    expect(sourceBefore).toContain("// defineHandler(");
    const loaded = await loadConfig(FIXTURE_PATH);
    const handlers = extractHandlers(loaded);

    vi.mocked(esbuild.build).mockClear();
    const files = await bundleHandlers({
      configPath: FIXTURE_PATH,
      handlers,
      hooksDir: OUTPUT_DIR,
      runtime: "node",
    });

    expect(esbuild.build).toHaveBeenCalledTimes(handlers.length);
    expect(
      existsSync(resolve(OUTPUT_DIR, "PreToolUse/blockDangerous.mjs")),
    ).toBe(false);
    expect(files).toHaveLength(2);

    const blockArtifact = files.find(({ name }) => name === "blockDangerous");
    const stopArtifact = files.find(({ name }) => name === "onStop");
    const handlerCode = blockArtifact?.contents ?? "";
    expect(handlerCode).toContain("process.stdin");
    expect(handlerCode).toContain("Generated by typed-claude-hooks");
    expect(handlerCode).toContain("local-define-handler-marker");
    expect(handlerCode).toContain('"defineHandler("');
    expect(handlerCode).toContain("`defineHandler(`");
    expect(handlerCode).not.toContain("stop-handler-only-marker");

    const stopHandlerCode = stopArtifact?.contents ?? "";
    expect(stopHandlerCode).toContain("stop-handler-only-marker");
    expect(stopHandlerCode).not.toContain("local-define-handler-marker");

    expect(blockArtifact?.wrapper.filePath).toBe(
      resolve(OUTPUT_DIR, "PreToolUse/blockDangerous.sh"),
    );
    expect(blockArtifact?.wrapper.contents).toContain("command -v node");

    expect(files[0].fileName).toBe("blockDangerous.mjs");
    expect(files[0].event).toBe("PreToolUse");

    for (const artifact of files) {
      mkdirSync(dirname(artifact.filePath), { recursive: true });
      writeFileSync(artifact.filePath, artifact.contents);
    }
    const baseInput = {
      session_id: "test",
      transcript_path: "/tmp/test.jsonl",
      cwd: "/tmp",
      marker: true,
    };
    const preToolUseInput = JSON.stringify({
      ...baseInput,
      hook_event_name: "PreToolUse",
      tool_name: "Bash",
      tool_input: { command: "ls" },
      tool_use_id: "tu_1",
    });
    const stopInput = JSON.stringify({
      ...baseInput,
      hook_event_name: "Stop",
      stop_hook_active: false,
    });
    expect(
      execFileSync("node", [blockArtifact?.filePath ?? ""], {
        encoding: "utf8",
        input: preToolUseInput,
      }),
    ).toContain("local-define-handler-marker:defineHandler(:defineHandler(");
    expect(
      execFileSync("node", [stopArtifact?.filePath ?? ""], {
        encoding: "utf8",
        input: stopInput,
      }),
    ).toContain("stop-handler-only-marker");

    expect(files.map(({ filePath }) => filePath)).toHaveLength(2);
    expect(files.every(({ filePath }) => filePath.endsWith(".mjs"))).toBe(true);
    expect(readFileSync(FIXTURE_PATH, "utf8")).toBe(sourceBefore);

    rmSync(OUTPUT_DIR, { recursive: true, force: true });
  });

  it("tree-shakes sibling handlers defined in re-exported local modules", async () => {
    const sourceBefore = readFileSync(RE_EXPORTED_HANDLERS_PATH, "utf8");
    expect(sourceBefore).toContain('const unrelatedString = "defineHandler(";');
    expect(sourceBefore).toContain(
      "// defineHandler( in an unrelated comment must remain untouched.",
    );
    const handlers = extractHandlers(await loadConfig(RE_EXPORT_FIXTURE_PATH));

    const files = await bundleHandlers({
      configPath: RE_EXPORT_FIXTURE_PATH,
      handlers,
      hooksDir: OUTPUT_DIR,
      runtime: "node",
    });

    const preToolUseArtifact = files.find(
      ({ name }) => name === "reExportedPreToolUse",
    );
    const stopArtifact = files.find(({ name }) => name === "reExportedStop");
    expect(preToolUseArtifact?.contents).toContain(
      "re-exported-pre-tool-use-marker",
    );
    expect(preToolUseArtifact?.contents).not.toContain(
      "re-exported-stop-marker",
    );
    expect(stopArtifact?.contents).toContain("re-exported-stop-marker");
    expect(stopArtifact?.contents).not.toContain(
      "re-exported-pre-tool-use-marker",
    );

    for (const artifact of files) {
      mkdirSync(dirname(artifact.filePath), { recursive: true });
      writeFileSync(artifact.filePath, artifact.contents);
    }
    const baseInput = {
      session_id: "test",
      transcript_path: "/tmp/test.jsonl",
      cwd: "/tmp",
      marker: true,
    };
    expect(
      execFileSync("node", [preToolUseArtifact?.filePath ?? ""], {
        encoding: "utf8",
        input: JSON.stringify({
          ...baseInput,
          hook_event_name: "PreToolUse",
          tool_name: "Bash",
          tool_input: { command: "ls" },
          tool_use_id: "tu_1",
        }),
      }),
    ).toContain("re-exported-pre-tool-use-marker:defineHandler(");
    expect(
      execFileSync("node", [stopArtifact?.filePath ?? ""], {
        encoding: "utf8",
        input: JSON.stringify({
          ...baseInput,
          hook_event_name: "Stop",
          stop_hook_active: false,
        }),
      }),
    ).toContain("re-exported-stop-marker");
    expect(readFileSync(RE_EXPORTED_HANDLERS_PATH, "utf8")).toBe(sourceBefore);

    rmSync(OUTPUT_DIR, { recursive: true, force: true });
  });

  it.each([
    [undefined, ".sh", "command -v deno"],
    ["bash", ".sh", "command -v deno"],
    ["powershell", ".ps1", "Get-Command deno"],
  ] as const)("adds the expected wrapper for shell %s", async (shell, extension, runtimeCheck) => {
    const files = await bundleHandlers({
      configPath: FIXTURE_PATH,
      handlers: [
        {
          event: "Stop",
          name: "onStop",
          ...(shell ? { shell } : {}),
        },
      ],
      hooksDir: OUTPUT_DIR,
      runtime: "deno",
    });

    expect(files[0].wrapper.filePath).toBe(
      resolve(OUTPUT_DIR, `Stop/onStop${extension}`),
    );
    expect(files[0].wrapper.contents).toContain(runtimeCheck);
  });
});
