import { describe, expect, it } from "vitest";
import { generateWrapper } from "../../src/compiler/wrapper-template.js";

describe("generateWrapper", () => {
  it("starts with sh shebang", () => {
    const code = generateWrapper("handler.mjs", "node");
    expect(code).toMatch(/^#!\/bin\/sh\n/);
  });

  it("contains the generated-by banner", () => {
    const code = generateWrapper("handler.mjs", "node");
    expect(code).toContain("Generated by typed-claude-hooks");
  });

  describe("node runtime", () => {
    it("checks for node availability", () => {
      const code = generateWrapper("handler.mjs", "node");
      expect(code).toContain("command -v node");
    });

    it("exits 2 with message when node is missing", () => {
      const code = generateWrapper("handler.mjs", "node");
      expect(code).toContain("exit 2");
      expect(code).toContain("Node.js is required but not installed");
    });

    it("execs node with the correct mjs file", () => {
      const code = generateWrapper("blockRm.mjs", "node");
      expect(code).toContain('exec node "$SCRIPT_DIR/blockRm.mjs"');
    });
  });

  describe("bun runtime", () => {
    it("checks for bun availability", () => {
      const code = generateWrapper("handler.mjs", "bun");
      expect(code).toContain("command -v bun");
    });

    it("exits 2 with message when bun is missing", () => {
      const code = generateWrapper("handler.mjs", "bun");
      expect(code).toContain("exit 2");
      expect(code).toContain("Bun is required but not installed");
    });

    it("execs bun with the correct mjs file", () => {
      const code = generateWrapper("blockRm.mjs", "bun");
      expect(code).toContain('exec bun "$SCRIPT_DIR/blockRm.mjs"');
    });
  });

  describe("deno runtime", () => {
    it("checks for deno availability", () => {
      const code = generateWrapper("handler.mjs", "deno");
      expect(code).toContain("command -v deno");
    });

    it("exits 2 with message when deno is missing", () => {
      const code = generateWrapper("handler.mjs", "deno");
      expect(code).toContain("exit 2");
      expect(code).toContain("Deno is required but not installed");
    });

    it("execs deno run --allow-all with the correct mjs file", () => {
      const code = generateWrapper("blockRm.mjs", "deno");
      expect(code).toContain(
        'exec deno run --allow-all "$SCRIPT_DIR/blockRm.mjs"',
      );
    });
  });
});
