import type { BuildOptions, BuildResult, Plugin } from "esbuild-wasm";
import {
  createSettingsSnippet,
  createWrapperArtifact,
  generateRuntime,
  planArtifactPaths,
} from "@typed-rocks/typed-claude-hooks/compiler";
import { discoverHandlers } from "./discover-handlers";
import type {
  CompileInput,
  CompileResponse,
  HandlerMetadata,
  PlaygroundArtifact,
  PlaygroundSettings,
  SourceDiagnostic,
} from "./types";
import {
  annotatePureDefineHandlers,
  authoringRuntime,
  configModule,
  runtimeModule,
  runtimeNamespace,
} from "./virtual-modules";

export interface EsbuildApi {
  build(options: BuildOptions): Promise<BuildResult>;
}

const hooksRoot = ".claude/hooks/typed-claude-hooks";

export async function buildHandlers(
  input: CompileInput,
  esbuild: EsbuildApi,
): Promise<CompileResponse> {
  const { fileName = "hooks.config.ts", requestId, source } = input;
  const discovered = discoverHandlers(source, fileName);
  if (discovered.diagnostics.some(({ severity }) => severity === "error")) {
    return errorResponse(requestId, discovered.diagnostics);
  }

  try {
    const plugin = virtualModulesPlugin(source, fileName);
    const artifacts = await Promise.all(
      discovered.handlers.map((handler) =>
        buildHandler(handler, plugin, esbuild),
      ),
    );
    return {
      type: "compile-result",
      requestId,
      status: "success",
      handlers: discovered.handlers,
      artifacts,
      diagnostics: discovered.diagnostics,
      settings: createSettings(artifacts),
    };
  } catch (error) {
    return errorResponse(requestId, buildDiagnostics(error, fileName, source));
  }
}

async function buildHandler(
  handler: HandlerMetadata,
  plugin: Plugin,
  esbuild: EsbuildApi,
): Promise<PlaygroundArtifact> {
  const { event, name } = handler;
  const planned = planArtifactPaths(handler, hooksRoot, "node");
  const { fileName, filePath } = planned;
  const result = await esbuild.build({
    stdin: {
      contents: `import { ${name} } from ${JSON.stringify(configModule)};\n${generateRuntime(`${name}.handler`)}`,
      loader: "js",
    },
    banner: { js: "// Generated by typed-claude-hooks - do not edit" },
    bundle: true,
    format: "esm",
    outfile: filePath,
    platform: "node",
    plugins: [plugin],
    treeShaking: true,
    write: false,
  });
  const contents = result.outputFiles?.[0]?.text;
  if (!contents || result.outputFiles?.length !== 1) {
    throw new Error(`Handler build produced no output for ${name}`);
  }
  return {
    ...planned,
    contents,
    wrapper: createWrapperArtifact(handler, filePath, "node"),
  };
}

// Derived from runtimeModule so a package rename cannot leave this filter behind.
const runtimeModulePattern = new RegExp(
  `^${runtimeModule.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`,
);

function virtualModulesPlugin(source: string, fileName: string): Plugin {
  const annotatedSource = annotatePureDefineHandlers(source, fileName);
  return {
    name: "playground-virtual-modules",
    setup(build) {
      build.onResolve({ filter: /^playground:hooks\.config\.ts$/ }, () => ({
        path: configModule,
        namespace: runtimeNamespace,
      }));
      build.onResolve({ filter: runtimeModulePattern }, () => ({
        path: runtimeModule,
        namespace: runtimeNamespace,
      }));
      build.onResolve({ filter: /^node:/ }, ({ path }) => ({
        path,
        external: true,
      }));
      build.onLoad({ filter: /.*/, namespace: runtimeNamespace }, ({ path }) =>
        path === configModule
          ? { contents: annotatedSource, loader: "ts" }
          : { contents: authoringRuntime, loader: "js" },
      );
    },
  };
}

function createSettings(artifacts: PlaygroundArtifact[]): PlaygroundSettings {
  return createSettingsSnippet(artifacts, ".");
}

function errorResponse(
  requestId: CompileInput["requestId"],
  diagnostics: SourceDiagnostic[],
): CompileResponse {
  return {
    type: "compile-result",
    requestId,
    status: "error",
    handlers: [],
    artifacts: [],
    diagnostics,
    settings: { hooks: {} },
  };
}

interface EsbuildMessage {
  text: string;
  location?: {
    file: string;
    line: number;
    column: number;
    length: number;
    lineText: string;
  } | null;
}

function buildDiagnostics(
  error: unknown,
  fileName: string,
  source: string,
): SourceDiagnostic[] {
  const messages = isEsbuildFailure(error) ? error.errors : [];
  return messages.length > 0
    ? messages.map((message) =>
        buildDiagnostic(message.text, fileName, source, message.location),
      )
    : [
        buildDiagnostic(
          error instanceof Error ? error.message : String(error),
          fileName,
          source,
        ),
      ];
}

function isEsbuildFailure(
  error: unknown,
): error is { errors: EsbuildMessage[] } {
  return (
    typeof error === "object" &&
    error !== null &&
    Array.isArray((error as { errors?: unknown }).errors)
  );
}

function buildDiagnostic(
  message: string,
  fileName: string,
  source: string,
  location?: EsbuildMessage["location"],
): SourceDiagnostic {
  const start = { line: 1, column: 1, offset: 0 };
  if (!location) {
    return {
      code: "PLAYGROUND_BUILD_FAILED",
      severity: "error",
      message,
      fileName,
      start,
      end: start,
    };
  }
  const sourceStart = sourcePosition(source, location.line, location.column);
  const end = {
    ...sourceStart,
    column: sourceStart.column + location.length,
    offset: sourceStart.offset + location.length,
  };
  return {
    code: "PLAYGROUND_BUILD_FAILED",
    severity: "error",
    message,
    fileName: isVirtualConfigLocation(location.file)
      ? fileName
      : location.file || fileName,
    sourceLine: location.lineText,
    start: sourceStart,
    end,
  };
}

function isVirtualConfigLocation(locationFile: string): boolean {
  return (
    locationFile === configModule ||
    locationFile === `${runtimeNamespace}:${configModule}`
  );
}

function sourcePosition(source: string, line: number, zeroBasedColumn: number) {
  const lines = source.split("\n");
  const offset =
    lines
      .slice(0, Math.max(0, line - 1))
      .map((text) => text.length + 1)
      .reduce((total, length) => total + length, 0) + zeroBasedColumn;
  return { line, column: zeroBasedColumn + 1, offset };
}
