// Generated by typed-claude-hooks - do not edit

// dist/utils.js
function clearUndefineds(obj) {
  const record = obj;
  for (const key of Object.keys(record)) {
    if (record[key] === void 0) {
      delete record[key];
    }
  }
  return obj;
}

// dist/authoring/define-handler.js
function defineHandler(event, ...rest) {
  const options = typeof rest[0] === "object" && rest[0] !== null && !Array.isArray(rest[0]) ? rest.shift() : void 0;
  const handler = rest[0];
  return clearUndefineds({
    ...options,
    event,
    handler,
  });
}

// hooks.config.ts
var onStop = /* @__PURE__ */ defineHandler("Stop", async (_input) => {
  return {};
});

// <stdin>
var __stdin = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", function (chunk) {
  __stdin += chunk;
});
process.stdin.on("end", function () {
  var __input;
  Promise.resolve()
    .then(function () {
      __input = JSON.parse(__stdin);
      return onStop.handler(__input);
    })
    .then(function (result) {
      if (result && result.hookSpecificOutput && !("hookEventName" in result.hookSpecificOutput)) {
        result = {
          ...result,
          hookSpecificOutput: {
            ...result.hookSpecificOutput,
            hookEventName: __input.hook_event_name,
          },
        };
      }
      if (result && Object.keys(result).length > 0) {
        process.stdout.write(JSON.stringify(result));
      }
    })
    .catch(function (err) {
      process.stderr.write(err && err.stack ? err.stack : String(err));
      process.exitCode = 2;
    });
});
