import {readFileSync} from "node:fs";
import {dirname, resolve} from "node:path";
import * as esbuild from "esbuild";
import {BuildResult} from "esbuild";
import type {HandlerOptions, Runtime} from "../types/mapping.js";
import {annotatePureHandlers} from "./annotate-pure-handlers.js";
import {loaderForPath} from "./esbuild-loader.js";
import type {HandlerEntry} from "./extract-handlers.js";
import {generateRuntime} from "./runtime-template.js";
import {generateBashWrapper, generatePowerShellWrapper} from "./wrapper-template.js";

export type {Runtime} from "../types/mapping.js";

export interface BundleOptions {
  configPath: string;
  handlers: HandlerEntry[];
  hooksDir: string;
  runtime: Runtime;
}

export interface PlannedArtifact extends HandlerOptions {
  contents: string;
  event: string;
  fileName: string;
  filePath: string;
  name: string;
  runtime: Runtime;
  wrapper: {
    contents: string;
    filePath: string;
  };
}

function createPlugin(): esbuild.Plugin {
  const transformed = new Map<string, esbuild.OnLoadResult>();
  return {
    name: "pure-define-handler",
    setup(build) {
      build.onLoad({filter: /\.[cm]?[jt]sx?$/}, (args) => {
        const filePath = resolve(args.path);
        if (/(^|[\\/])node_modules([\\/]|$)/.test(filePath)) return undefined;
        const cached = transformed.get(filePath);
        if (cached) return cached;

        const result = {
          contents: annotatePureHandlers(readFileSync(filePath, "utf8"), filePath),
          loader: loaderForPath(filePath),
        };
        transformed.set(filePath, result);
        return result;
      });
    },
  };
}

async function esbuildSingleHandler(name: string, absConfigPath: string, filePath: string, plugin: esbuild.Plugin) {
  const contents = [`import { ${name} } from ${JSON.stringify(absConfigPath)};`, generateRuntime(`${name}.handler`)].join(
    "\n",
  );
  return await esbuild.build({
    stdin: {
      contents,
      resolveDir: dirname(absConfigPath),
    },
    banner: {js: "// Generated by typed-claude-hooks - do not edit"},
    bundle: true,
    format: "esm",
    outfile: filePath,
    platform: "node",
    plugins: [plugin],
    treeShaking: true,
    write: false,
  });
}

function createWrapperScript(isPowerShell: boolean, fileName: string, runtime: Runtime, filePath: string) {
  return {
    contents: isPowerShell ? generatePowerShellWrapper(fileName, runtime) : generateBashWrapper(fileName, runtime),
    filePath: filePath.replace(/\.mjs$/, isPowerShell ? ".ps1" : ".sh"),
  };
}

function readSingleTextOrThrow(result: BuildResult, name: string) {
  const contents = result.outputFiles?.[0]?.text;
  if (!contents || result.outputFiles?.length !== 1) {
    throw new Error(`Handler build produced no output for ${name}`);
  }
  return contents;
}

async function bundleHandler(
  handler: HandlerEntry,
  {hooksDir, runtime, configPath}: BundleOptions,
  plugin: esbuild.Plugin,
) {
  const absConfigPath = resolve(configPath);
  const {name, event, ...handlerOptions} = handler;
  const fileName = `${name}.mjs`;
  const filePath = resolve(hooksDir, event, fileName);
  const result = await esbuildSingleHandler(name, absConfigPath, filePath, plugin);
  const contents = readSingleTextOrThrow(result, name);
  const isPowerShell = handlerOptions.shell === "powershell";
  const wrapper = createWrapperScript(isPowerShell, fileName, runtime, filePath);
  return {
    ...handlerOptions,
    contents,
    event,
    fileName,
    filePath,
    name,
    runtime,
    wrapper,
  };
}

export async function bundleHandlers(bundleOptions: BundleOptions): Promise<PlannedArtifact[]> {
  const plugin: esbuild.Plugin = createPlugin();

  return Promise.all(bundleOptions.handlers.map((handler) => bundleHandler(handler, bundleOptions, plugin)));
}
