import type { HookEvent } from "../types/index.js";

export const HOOK_EVENTS: Record<HookEvent, true> = {
  PreToolUse: true,
  PostToolUse: true,
  PostToolUseFailure: true,
  PostToolBatch: true,
  Notification: true,
  UserPromptSubmit: true,
  UserPromptExpansion: true,
  SessionStart: true,
  SessionEnd: true,
  Stop: true,
  StopFailure: true,
  SubagentStart: true,
  SubagentStop: true,
  PreCompact: true,
  PostCompact: true,
  PermissionRequest: true,
  PermissionDenied: true,
  Setup: true,
  TeammateIdle: true,
  TaskCreated: true,
  TaskCompleted: true,
  Elicitation: true,
  ElicitationResult: true,
  ConfigChange: true,
  WorktreeCreate: true,
  WorktreeRemove: true,
  InstructionsLoaded: true,
  CwdChanged: true,
  FileChanged: true,
  MessageDisplay: true,
};
