import type { Runtime } from "../types/mapping.js";

export type { Runtime } from "../types/mapping.js";

const runtimeArgsByRuntime: Record<Runtime, readonly string[]> = {
  node: [],
  bun: [],
  deno: ["run", "--allow-all"],
};

export function runtimeCommand(runtime: Runtime): string {
  return runtime;
}

export function runtimeArgs(runtime: Runtime): readonly string[] {
  return runtimeArgsByRuntime[runtime];
}

function runtimeInvocation(runtime: Runtime): string {
  return [runtimeCommand(runtime), ...runtimeArgs(runtime)].join(" ");
}

export function generateBashWrapper(
  mjsFileName: string,
  runtime: Runtime,
): string {
  const command = runtimeCommand(runtime);
  const invocation = runtimeInvocation(runtime);
  return `#!/usr/bin/env bash
# Generated by typed-claude-hooks - do not edit
if ! command -v ${command} >/dev/null 2>&1; then
  echo "typed-claude-hooks: ${command} is required but not installed" >&2
  exit 2
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec ${invocation} "$SCRIPT_DIR/${mjsFileName}" "$@"
`;
}

export function generatePowerShellWrapper(
  mjsFileName: string,
  runtime: Runtime,
): string {
  const command = runtimeCommand(runtime);
  const invocation = runtimeInvocation(runtime);
  return `# Generated by typed-claude-hooks - do not edit
if (-not (Get-Command ${command} -ErrorAction SilentlyContinue)) {
  [Console]::Error.WriteLine("typed-claude-hooks: ${command} is required but not installed")
  exit 2
}
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$scriptPath = Join-Path $scriptDir "${mjsFileName}"
& ${invocation} $scriptPath @args
exit $LASTEXITCODE
`;
}
