export type Runtime = "node" | "bun" | "deno";

interface RuntimeConfig {
  command: string;
  execArgs: string;
  name: string;
  installUrl: string;
}

const runtimeConfigs: Record<Runtime, RuntimeConfig> = {
  node: {
    command: "node",
    execArgs: "node",
    name: "Node.js",
    installUrl: "https://nodejs.org",
  },
  bun: {
    command: "bun",
    execArgs: "bun",
    name: "Bun",
    installUrl: "https://bun.sh",
  },
  deno: {
    command: "deno",
    execArgs: "deno run --allow-all",
    name: "Deno",
    installUrl: "https://deno.land",
  },
};

export function generateWrapper(mjsFileName: string, runtime: Runtime): string {
  const config = runtimeConfigs[runtime];
  return `#!/bin/sh
# Generated by typed-claude-hooks — do not edit
if ! command -v ${config.command} >/dev/null 2>&1; then
  echo "typed-claude-hooks: ${config.name} is required but not installed. Install it from ${config.installUrl}" >&2
  exit 2
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec ${config.execArgs} "$SCRIPT_DIR/${mjsFileName}"
`;
}
