#!/bin/sh
# Generated by typed-claude-hooks — do not edit
if ! command -v node >/dev/null 2>&1; then
  echo "typed-claude-hooks: Node.js is required but not installed. Install it from https://nodejs.org" >&2
  exit 2
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
exec node "$SCRIPT_DIR/blockDangerous.cjs"
